#!/usr/bin/env bash
# script configure a new Ubuntu machine to respect some requirements:
# install nginx on your web-01
# Nginx should listening on  port 80
# When querying Nginx at its root / with GET request using curl,
# it must return a page that contains the string Hello World!

apt update
apt-get install -y nginx

ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index*
service nginx restart
