#!/usr/bin/env bash
# script configure a new Ubuntu machine to respect some requirements:
# install nginx on your web-01
# Nginx should listening on  port 80
# When querying Nginx at its root / with GET request using curl,
# it must return a page that contains the string Hello World!
# configure so that /redirect_me is redirecting to another page

apt update
apt-get install -y nginx

ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index*

link="https://twitter.com/jamesmatics"
replacement_str="server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 $link;\n\t}"
sed -i "s|server_name _;|$replacement_str|" /etc/nginx/sites-available/default
service nginx restart
