#!/usr/bin/env bash
# script configure a new Ubuntu machine to respect some requirements:
# install nginx on your web-01
# Nginx should listening on  port 80
# When querying Nginx at its root / with GET request using curl,
# it must return a page that contains the string Hello World!
# configure so that /redirect_me is redirecting to another page

# install nginx
apt update
apt-get install -y nginx

# allow ubuntu firewall
ufw allow 'Nginx HTTP'

# modify what is served
echo "Hello World!" > /var/www/html/index*

# redirect this page
link="https://twitter.com/jamesmatics"
sed -i "s|server_name _;|$replacement_str|" /etc/nginx/sites-available/default
replacement_str="server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 $link;\n\t}\n\tadd_header X-Served-By "72117-web-01";\n\terror_page 404 /404.html;\n\tlocation =/404.html {\n\t\troot /var/www/html/;\n\t\tinternal;\n\t}\n"
# create a not found page
echo "Ceci n'est pas une page" > /var/www/html/404.html

service nginx restart
