#!/usr/bin/env bash
# install and configure HAproxy on this server
# distribute requests using a roundrobin algorithm
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.5
sudo apt-get install haproxy=2.5.\*
sudo sed -i "11 a\ ENABLED=1"  /etc/default/haproxy
sudo sed -i '21,28d' /etc/haproxy/haproxy.cfg
sudo sed -i "19 a\ \nlisten listener\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption forwardfor\n\toption httpclose\n\tserver 72117-web-01 52.91.134.149:80 check\n\tserver 72117-web-02 54.90.62.231:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
