#!/usr/bin/env bash
# This script displays "Best School" 10 times

i=10
while [[ "$i" -ne 0 ]]; do
	if [[ "$i" -eq 3 ]]; then
		echo "good luck"
	elif [[ "$i" -eq 7 ]]; then
		echo "bad luck"
	else
		echo "Best School"
	fi
	i=$((i - 1))
done
