#!/usr/bin/env bash
# gives information about the school file

FILE="./school"
if [ -e "$FILE" ]; then
	echo "school file exists"
	if [ -f "$FILE" ]; then
		echo "school is a regular file"
	fi
	if [ -s "$FILE" ]; then
		echo "school file is not empty"
	else
		echo "school file is not empty"
	fi
else
	echo "school file does not exist"
fi
