#!/usr/bin/bash
# installs ufw and allow to listen at port
# 22, 443, 80

if dpkg ufw &> /dev/null ; then
	sudo apt remove ufw
	sudo apt install ufw
	sudo ufw allow 22
	sudo ufw allow 443
	sudo ufw allow 80
else;
	sudo apt install ufw
	sudo ufw allow 22
	sudo ufw allow 443
	sudo ufw allow 80
fi
