#!/usr/bin/bash
# installs ufw and allow to listen at port
# 22, 443, 80

if dpkg ufw &> /dev/null ; then
	sudo apt remove ufw
	sudo apt install ufw
	sudo ufw default deny incoming
	sudo ufw allow 22/OpenSSH
	sudo ufw allow 443/HTTPS
	sudo ufw allow 80/HTTP
	sudo ufw enable
else
	sudo apt install ufw
	sudo ufw default deny incoming
	sudo ufw allow 22/OpenSSH
	sudo ufw allow 443/HTTPS
	sudo ufw allow 80/HTTP
	sudo ufw enable
fi
