#!/usr/bin/bash
# installs ufw and allow to listen at port
# 22, 443, 80

if dpkg ufw &> /dev/null ; then
	sudo apt remove ufw
	sudo apt install ufw
	sudo ufw allow 22
	sudo ufw allow 443
	sudo ufw allow 80
else
	sudo apt install ufw
	sudo ufw allow 22
	sudo ufw allow 443
	sudo ufw allow 80
fi

sudo sed -i "s|DEFAULT_FORWARD_POLICY='DROP'|DEFAULT_FORWARD_POLICY='ACCEPT'|" /etc/default/ufw

sudo sed -i "s|commit|# The firewall redirects port 8080/TCP to port 80/TCP /n*nat/n:PREROUTING ACCEPT [0:0]/nA PREROUTING -p tcp --dport 8080 -j REDIRECT --to port 80/ncommit|" /etc/ufw/before.rules
