#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.old
cp /etc/hosts ~/hosts.new
sed -i s/^127.*localhost/"127.0.0.2\tlocalhost"/ ~/hosts.new
printf "8.8.8.8\tfacebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
